#define GLEW_STATIC
#include "arcobj.h"
#include "array_list.h" //from data-structures
#include "batch.h"
#include "circ.h"
#include "collision.h"
#include "groups.h"
#include "lines.h"
#include "matrix.h"
#include "poly.h"
#include "quadtree.h"
#include "rect.h"
#include "spatial_map.h"
#include "shape.h"
#include "transform.h"
#include "window.h"
#include "world.h"
